server:
  port: 8080
spring:
  jackson:
    serialization:
      write_dates_as_timestamps: false
  redis:
    host: localhost
    port: 6379
  cache:
    type: ehcache
    ehcache:
      config: classpath:ehcache.xml
  profiles:
    include: db
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        ddl-auto: update
    open-in-view: false
    generate-ddl: true